---
# tasks file for otus-nginx
- name: Install epel-release
  yum:
    name: epel-release
    state: latest
  tags:
    - package
    - epel

- name: Install nginx
  yum:
    name: nginx
    state: latest
  tags:
    - package
    - nginx

- name: Enable nginx
  systemd:
    name: nginx
    enabled: yes
  notify: Restart nginx


- name: Copy config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: Restart nginx


